### ISSUE TITLE
No ligatures with Arabic

### ISSUE THREAD

**Issue by jbezos** [khaledhosny/harftex#2]
I'd like to see if the bidi algorithm in `babel` works with `harftex`, and which changes would be necessary.

So, I've downloaded the binaries for Windows from http://ctan.ijs.si/mirror/w32tex/current/harftex-w32.tar.xz, but the sample files doesn't show the text correctly - only isolated forms. I've added the following features, and there are a few ligatures, but not all: +fina;+init;+medi;+isol;+med2;+mset;+rtla;+curs;+falt. I've also installed the files available here, with no luck.

**Comment by khaledhosny** [comment]
`harftex --credits` would show the versions of used library, and I suspect that a different version of HarfBuzz is used in the w32tex binaries than I have in my own builds, and that might be causing some problem.

**Comment by jbezos** [comment]
Here is:

```
This is HarfTeX, Version 0.1.2 (TeX Live 2019/W32TeX)

HarfTeX merges and builds upon (parts of) the code from these projects:

luatex    : Hans Hagen, Hartmut Henkel, Taco Hoekwater, Luigi Scarso
tex       : Donald Knuth
etex      : Peter Breitenlohner, Phil Taylor and friends
omega     : John Plaice and Yannis Haralambous
aleph     : Giuseppe Bilotta
pdftex    : Han The Thanh and friends
kpathsea  : Karl Berry, Olaf Weber and others
lua       : Roberto Ierusalimschy, Waldemar Celes and Luiz Henrique de Figueiredo
metapost  : John Hobby, Taco Hoekwater, Luigi Scarso, Hans Hagen and friends
pplib     : Pawe\l Jackowski
fontforge : George Williams (partial)

Compiled with libpng 1.6.37; using 1.6.37
Compiled with lua version 5.3.5
Compiled with mplib version 2.00
Compiled with zlib 1.2.11; using 1.2.11
Compiled with harfbuzz 2.5.0; using 2.5.0
```
And the libraries:

```
09/07/2015  15:32            18.624 api-ms-win-core-file-l1-2-0.dll
09/07/2015  15:32            18.624 api-ms-win-core-file-l2-1-0.dll
09/07/2015  15:32            21.184 api-ms-win-core-localization-l1-2-0.dll
09/07/2015  15:32            19.136 api-ms-win-core-processthreads-l1-1-1.dll
09/07/2015  15:32            19.136 api-ms-win-core-synch-l1-2-0.dll
09/07/2015  15:32            18.624 api-ms-win-core-timezone-l1-1-0.dll
09/07/2015  15:32            22.720 api-ms-win-crt-convert-l1-1-0.dll
09/07/2015  15:32            19.136 api-ms-win-crt-environment-l1-1-0.dll
09/07/2015  15:32            20.672 api-ms-win-crt-filesystem-l1-1-0.dll
09/07/2015  15:32            19.648 api-ms-win-crt-heap-l1-1-0.dll
09/07/2015  15:32            19.136 api-ms-win-crt-locale-l1-1-0.dll
09/07/2015  15:32            29.376 api-ms-win-crt-math-l1-1-0.dll
09/07/2015  15:32            26.816 api-ms-win-crt-multibyte-l1-1-0.dll
09/07/2015  15:32            19.648 api-ms-win-crt-process-l1-1-0.dll
09/07/2015  15:32            23.232 api-ms-win-crt-runtime-l1-1-0.dll
09/07/2015  15:32            24.768 api-ms-win-crt-stdio-l1-1-0.dll
09/07/2015  15:32            24.768 api-ms-win-crt-string-l1-1-0.dll
09/07/2015  15:32            21.184 api-ms-win-crt-time-l1-1-0.dll
09/07/2015  15:32            19.136 api-ms-win-crt-utility-l1-1-0.dll
25/05/2019  07:25         5.790.208 harftex.dll
18/04/2019  06:03        27.534.336 icudt64.dll
12/04/2019  15:19           170.496 lua53.dll
09/06/2016  15:46           440.120 msvcp140.dll
18/02/2011  16:40           773.968 msvcr100.dll
09/07/2015  15:33           900.288 ucrtbase.dll
09/06/2016  15:46            83.784 vcruntime140.dll
```

**Comment by khaledhosny** [comment]
OK, so as I suspected the w23tex binary is using HarfBuzz 2.5.0 and I’m still using 2.4.0. I think I know what changed in HarfBuzz that might be causing trouble here, I’ll update to HarfBuzz 2.5.0 and check.

**Comment by khaledhosny** [comment]
Patch sent to [TeX Live mailing list](https://tug.org/pipermail/tex-live/2019-May/043706.html), there is small issue in the HarfBuzz build scripts in TeX Live that was masked in previous releases.

**Comment by khaledhosny** [comment]
Can you try with the latest w32tex binary?

**Comment by jbezos** [comment]
It works. Now I'm adapting `babel` to the harf renderer (and I was able to typeset correctly some documents, after a few minor changes).

**Comment by khaledhosny** [comment]
Great.

**Comment by khaledhosny** [comment]
At some point I’d like to handle bidi in the renderer in a way or another (potentially using ICU), and I understand that babl has some bidi support as well, so I need to see if putting it in the renderer and make it it on by default is a better approach or if it would cause any conflicts.

**Comment by jbezos** [comment]
Babel doesn't impose any bidi algorithm. It must be set explicitly as a package option (currently is `bidi=basic` for luatex). So, nothing prevents using other algorithms.

**Comment by jbezos** [comment]
Thinking about this, I was wondering if `harftex` provides (or will provide) some access to the ICU API with lua.

**Comment by khaledhosny** [comment]
Yes, it will probably be in the form of an `icu` module in Lua that exposes some of ICU APIs, though I haven’t done any work on this area yet.

**Comment by jbezos** [comment]
Definitely, `harftex` looks great. Thank you.
