### ISSUE TITLE
removal of fontloader library breaks the luatexja package

### ISSUE THREAD

**Issue by u-fischer** [khaledhosny/harftex#6]
```
\documentclass{article}
\usepackage{harfload}
\usepackage{luatexja}

\begin{document}
abc
\end{document}
```

fails with 

~~~~
texmf-dist/tex/luatex/luatexja/ltj-jfont.lua:811: attempt to index a nil value 
(global 'fontloader')
stack traceback:
	...exlive/2019/texmf-dist/tex/luatex/luatexja/ltj-jfont.lua:811: in main chunk
	[C]: in function 'require'
	c:/texlive/2019/texmf-dist/tex/luatex/luatexja/luatexja.lua:17: in local 'load_
module'
	c:/texlive/2019/texmf-dist/tex/luatex/luatexja/luatexja.lua:106: in main chunk
	[C]: in function 'dofile'
	[\directlua]:1: in main chunk.
l.181 }
~~~~

If the library is really removed, it would be good to notify the authors so that they can check their options. (btw: the speedata publisher uses the library too).

**Comment by khaledhosny** [comment]
Not sure what more should I do other than mentioning it in the release note. AFIAIk the old fontloader was deprecated in LuaTeX for a few releases already, so packages had enough time to look for replacement. If they are still using it, then probably they really need it and HarfTeX will be unsuitable for these packages.

**Comment by u-fischer** [comment]
I notified the two main parties concerned by this change.

**Comment by khaledhosny** [comment]
Thanks @u-fischer. We can close this issue then.

**Comment by luigiScarso** [comment]
> Not sure what more should I do other than mentioning it in the release note. AFIAIk the old fontloader was deprecated in LuaTeX for a few releases already

Hm, not that we (luatex team) know.  Is there some sign in the manual or in some commit message ? In any case, the ff font loader will stay in texlive 2020.

**Comment by khaledhosny** [comment]
I can bring it back if this what people want. It felt od too keep two font loading libraries, one of them is outdated and don't support new versions of OpenType spec.

**Comment by kberry** [comment]
just from the point of view of keeping harftex and luahbtex as close as possible, I think it's desirable to bring it back. IMHO ...

**Comment by khaledhosny** [comment]
It also decreased the binary size from 8MB to 4.6MB and I thought others cared about binary size much. I impartial, so it is coming back in next release. This also saves me the trouble of debugging #5.
